// Asset paths and small type aliases shared by AudioEngine and its tests —
// spec §9.1's layer table.
//
// [DEVIATION] These point at .wav placeholders generated by
// scripts/gen-placeholder-audio.mjs, not the .m4a the spec's final
// production pipeline calls for (plan §2.2: real assets need ffmpeg on
// the content producer's machine). AudioContext.decodeAudioData() sniffs
// the actual file bytes, so this is purely a path/extension swap — no
// AudioEngine code depends on the format. Update these back to .m4a once
// real recorded/produced audio replaces the placeholders.
import type { BedLayerId } from '../core/types';

export type { BedLayerId };

export type SfxId = 'matchSuccess' | 'starRise';

export const BED_LAYER_URLS: Record<Exclude<BedLayerId, 'brownNoise'>, string> = {
  rain: '/audio/bed/rain.wav',
  crickets: '/audio/bed/crickets.wav',
  asmrTaps: '/audio/bed/asmr-taps.wav',
};

export const SFX_URLS: Record<SfxId, string> = {
  matchSuccess: '/audio/sfx/match-success.wav',
  starRise: '/audio/sfx/star-rise.wav',
};

export function voiceWordUrl(index: number): string {
  return `/voice/${String(index)}.wav`;
}
